apiVersion: v1
kind: Service
metadata:
  name: heureka-api-gateway
  namespace: statex-apps
  labels:
    app: heureka-api-gateway
    managed-by: k8s-migration
spec:
  type: ClusterIP
  selector:
    app: heureka-api-gateway
  ports:
    - protocol: TCP
      port: 3801
      targetPort: 3801
      name: app
